DROP TABLE IF EXISTS Cities;

CREATE TABLE Cities (
  Id SERIAL PRIMARY KEY,
  Title VARCHAR(100) NOT NULL,
  Author VARCHAR(500) NOT NULL,
  Genre VARCHAR(1000),
  IsCheckedOut BOOLEAN NOT NULL DEFAULT(FALSE),
  Rating NUMERIC(5,2),
  DatePurchased DATE
)
